### ISSUE TITLE
Not specifying a file on setup causes error

### ISSUE THREAD

**Issue by AbderrSfa** [barimehdi77/ft_transcendence#10]
If I complete my profile without adding a profile picture, the API returns ERROR 500.
<img width="601" alt="Screen Shot 2022-08-18 at 4 07 35 PM" src="https://user-images.githubusercontent.com/58333462/185429808-d0496c82-6c0f-45e4-8a57-5ae5f1caaced.png">

**Comment by barimehdi77** [comment]
This error is fixed!

**Comment by AbderrSfa** [comment]
This error is back

**Comment by barimehdi77** [comment]
I deleted a line of the code when I added try catch and that cause the error again
