### ISSUE TITLE
add two buttons in profile page

### ISSUE THREAD

**Issue by barimehdi77** [barimehdi77/ft_transcendence#33]
you need to add two buttons to the profile page:

1. First one for sending a friend request (see the docs [here](https://github.com/barimehdi77/ft_transcendence/tree/main/api/src/friends#post-send-friend-request)).
2. Second on for blocking a user (see the docs [here](https://github.com/barimehdi77/ft_transcendence/tree/main/api/src/friends#post-block-user))

those buttons will change if :

1. the two users are already friends (will display UNFRIEND button)
2. the two a user was blocking this specific user (will display UNBLOCK button)/

FOR MORE INFORMATIONS CONTACT ME

**Comment by AbderrSfa** [comment]
Done
