### ISSUE TITLE
strange error in rooms and Dms

### ISSUE THREAD

**Issue by barimehdi77** [barimehdi77/ft_transcendence#37]
notification pop up with `res.map`

<img width="2056" alt="Screen Shot 2022-09-18 at 13 04 52" src="https://user-images.githubusercontent.com/54292953/190901610-0fa949d0-fda6-49ed-a624-35164565f110.png">

**Comment by aerragha** [comment]
This problem happened when you merged the chat part, you used `getAllUsers("friends") `instead of `getAllUsers("/user/fiind").`

**Comment by aerragha** [comment]
The update added to dev branch
