### ISSUE TITLE
navbar does not displayed after login for the first time

### ISSUE THREAD

**Issue by barimehdi77** [barimehdi77/ft_transcendence#5]
![Uploading Screen Shot 2022-08-10 at 23.00.28.png…]()

**Comment by AbderrSfa** [comment]
Fixed

**Comment by barimehdi77** [comment]
This is the image
<img width="1500" alt="Screen Shot 2022-08-10 at 23 00 28" src="https://user-images.githubusercontent.com/54292953/184204740-6622ea9c-beb9-492b-b53c-97840be3f96c.png">

**Comment by AbderrSfa** [comment]
Fixed
