### ISSUE TITLE
API returns error when fetching on /profile/me

### ISSUE THREAD

**Issue by AbderrSfa** [barimehdi77/ft_transcendence#6]
When I fetch on /profile/me I get and ERROR 500
<img width="1221" alt="Screen Shot 2022-08-11 at 11 22 36 AM" src="https://user-images.githubusercontent.com/58333462/184113692-85c1078c-2af9-4819-bbf5-64ea1b7b33b0.png">

**Comment by barimehdi77** [comment]
Fixed
